#!/bin/bash
# number of threads:
for t in 1 2 4 8
do
    #echo NUMT = $t
    # number of subdivisions:
    for s in 2  8  32  128  512  2048  4096 8192
    do
        #echo NUMTRIALS = $s
        g++ -DNUMNODES=$s -DNUMT=$t proj2.cpp -o proj -lm -fopenmp
        ./proj
        echo -n ","
    done
    echo
done