#!/bin/bash
# number of threads:
for t in 1 2 4 6 8
do
    #echo NUMT = $t
    # number of subdivisions:
    for s in 2 4 8 16 32 64 128 256 512 1024 2048 3072 4096
    do
        #echo NUMTRIALS = $s
        g++ -DNUMTRIALS=$s -DNUMT=$t proj1.cpp -o proj -lm -fopenmp
        ./proj
        echo -n ","
    done
    echo
done