#!/bin/bash
# number of threads:

for t in 1
do
    #echo NUMT = $t
    # number of subdivisions:
    for s in 8 64 128 256 512 1024 8192 128000 512000 1024000 2048000 4096000 8192000
    do
        #echo NUMTRIALS = $s
        g++ -DARRSIZE=$s -DNUMT=$t proj4.cpp -o proj -lm -fopenmp
        ./proj
        #echo -n ","
    done
    echo
done